# Generated by Django 3.0.5 on 2021-08-02 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculateNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeForStudentloginPage', models.CharField(max_length=300, null=True)),
                ('NoticeForStudentExamTimeTable', models.CharField(max_length=300, null=True)),
                ('NoticeForStudentQuestionPeparLoad', models.CharField(max_length=300, null=True)),
                ('NoticeForEveryOnearjunt', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('Subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Subject_name', models.CharField(max_length=100)),
                ('Duration', models.IntegerField(default=30, max_length=10)),
                ('marks', models.IntegerField(max_length=100)),
                ('Exammonth', models.CharField(default='oct', max_length=10)),
                ('Examyear', models.IntegerField(default=2021, max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sem', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Student/')),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatno', models.IntegerField()),
                ('papercode', models.CharField(max_length=20)),
                ('questionid', models.CharField(max_length=50)),
                ('correctanswer', models.CharField(max_length=100)),
                ('selectedanswer', models.CharField(max_length=100)),
                ('questionmarks', models.IntegerField(max_length=100)),
                ('obtainedmarks', models.IntegerField(max_length=100)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=300)),
                ('Option1', models.CharField(max_length=200)),
                ('Option2', models.CharField(max_length=200)),
                ('Option3', models.CharField(max_length=200)),
                ('Option4', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200)),
                ('marks', models.PositiveIntegerField()),
                ('Paper_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Exams')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatno', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('Subject_name', models.CharField(max_length=100)),
                ('papercode', models.CharField(max_length=100)),
                ('Totalmarks', models.PositiveIntegerField()),
                ('obtainedmarks', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Paper_code', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('FromTime', models.TimeField()),
                ('ToTime', models.TimeField()),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Start', 'Start'), ('End', 'End')], default='Scheduled', max_length=20)),
                ('course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Course')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Semester'),
        ),
    ]
